image: tiangolo/docker-with-compose

services:
  - docker:20.10-dind

stages:
  - deploy

deploy-docker:
  stage: deploy
  image: tiangolo/docker-with-compose
#  before_script:
#    - docker stop $(docker ps -aq -f ancestor=jarvis)
#    - docker rm $(docker ps -aq -f ancestor=jarvis)
#    - docker rmi jarvis
  script:
    - docker build src/ -f src/Dockerfile -t jarvis --build-arg BOT_TOKEN=$BOT_TOKEN
    - docker run jarvis
  tags:
    - deploy
    - staging
